version: 2.1
jobs:
  linting-dockerfile:
    docker:
      - image: docker
    steps:
      - checkout
      - run:
          name: linting dockerfile
          command: docker run --rm -i hadolint/hadolint < Dockerfile

  upload-image:
    docker:
      - image: docker
    steps:
      - checkout
      - run:
          name: login to docker hub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run:
          name: build docker image
          command: |
            mkdir /code
            cp index.html /code
            docker build -t $DOCKERHUB_USERNAME/capstone /code
      - run:
          name: push docker image
          command: docker push $DOCKERHUB_USERNAME/capstone
workflows:
  default:
    jobs:
      - linting-dockerfile
      - upload-image:
          requires: [linting-dockerfile]
          context:
            - DOCKERHUB