version: 2.1
jobs:
  linting-dockerfile:
    machine: true
    steps:
      - checkout
      - run: docker run --rm -i hadolint/hadolint < Dockerfile

  upload-image:
    machine: true
    steps:
      - checkout
      - run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run: docker build -t $DOCKERHUB_USERNAME/capstone .
      - run: docker push $DOCKERHUB_USERNAME/capstone

workflows:
  default:
    jobs:
      - linting-dockerfile
      - upload-image:
          requires: [linting-dockerfile]
          context:
            - DOCKERHUB