version: 2.1
jobs:
  linting-dockerfile:
    machine: true
    steps:
      - checkout
      - run: 
          name: linting docker file
          command: docker run --rm -i hadolint/hadolint < Dockerfile

  upload-image:
    machine: true
    steps:
      - checkout
      - run: 
          name: login to docker hub
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run: 
          name: build docker image
          command: docker build -t $DOCKERHUB_USERNAME/capstone .
      - run: 
          name: push docker image
          command: docker push $DOCKERHUB_USERNAME/capstone

workflows:
  default:
    jobs:
      - linting-dockerfile
      - upload-image:
          requires: [linting-dockerfile]
          context:
            - DOCKERHUB