---

- name: update cash
  apt:
    update_cache: yes

- name: Install some packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - gnupg 
    - lsb-release

- name: Add Docker’s official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name:  set up the stable repository
  shell: |
    echo \
      "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: update cash
  apt:
    update_cache: yes

- name: Install some packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: add ubuntu user to docker group
  shell: sudo usermod -aG docker ubuntu