apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.tag }}
spec:
  # type: LoadBalancer
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: app-{{ .Values.tag }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP